### PR TITLE
Add regex suggested by JOSS review

### PR DESCRIPTION
**Pull request by florian-huber**
Addressing ambiguous regex for formula search in ``derive_formula_from_name`` (#94).
(suggested regex seems good based on first tests with https://regex101.com/)

### CODE REVIEW

**Comment by florian-huber** [comment]
Hi @sverhoeven . It looks like with the current ``pylint`` version we get a weird looking error message. I tried to move back to to an older version of pylint in PR #98, but failed to do so. Do you have any idea on how to fix this? 
Thanks!

**Comment by sverhoeven** [comment]
I am able to reproduces the error in the https://github.com/matchms/matchms/tree/dead-linter branch on GitHub and locally. Will investigate further.

**Comment by sverhoeven** [comment]
It's a pylint isort5 incompatibility problem. There is a PR in pylint to make it compatible,for now I restricted the isort version.

**Review by sverhoeven — APPROVED** [review]

**Comment by florian-huber** [comment]
Great, thanks a lot for solving the issue @sverhoeven !

**Pull request merged**
