### PR TITLE
Small bug fixing (during running of pipeline)

### PR DESCRIPTION
**Pull request by niekdejonge**
Some small filter bugfixes:
- fixed get netural mass handling None. Getting smiles = None would result in the pipeline breaking. 
- Add check is_valid_inchikey to not break workflow when inchikey is None
- Remove wrong warnings and make warnings more informative
- Added changelog for previous PR's
- and more...

### CODE REVIEW

**Comment by florian-huber** [comment]
@niekdejonge let me know once #509 is up to date with #507 again. Right now we accumulated too many changes with respect to this branch, which makes it hard to compare on the code side.

**Comment by niekdejonge** [comment]
@florian-huber #509 and #507 are up to date again and merge conflicts should have been resolved

**Comment by florian-huber** [comment]
@niekdejonge looks pretty good. I edited a bit of code for better readability (*I hope*) --> #521

Just have a look at those suggestions and feel free to merge if it's OK.

**Review by florian-huber — APPROVED** [review]

**Comment by niekdejonge** [comment]
@florian-huber Thanks for all the code reviews! I added some final refactoring and cleaning in #522, but will go ahead and merge this PR already.

**Pull request merged**
