### PR TITLE
Update save_as_msp.py

### PR DESCRIPTION
**Pull request by Adafede**
Consistent naming with other functions

### CODE REVIEW

**Review by florian-huber — APPROVED** [review]
Thanks for catching this. Changes look good!

**Comment by florian-huber** [comment]
Thanks for the pull request @Adafede !

Feel free to also add your name to https://github.com/matchms/matchms/blob/master/.zenodo.json and https://github.com/matchms/matchms/blob/master/CITATION.cff

**Comment by Adafede** [comment]
Very welcome @florian-huber!

I do not have the feeling such small fix deserves to be in the authors 😝 

Hopefully I'll be able to suggest some more meaningful things soon!

**Comment by florian-huber** [comment]
Even better 😄

**Pull request merged**
