### PR TITLE
Vectorise matrix similarity functions

### PR DESCRIPTION
**Pull request by tornikeo**
Addressing #637. I rewrote the `njitted` functions using plain matmul operations, using `numpy`. This [is around x50 times faster](https://colab.research.google.com/drive/1dYvdcbkUUOubgjPAZTtsfpG5Z7duc1kw?usp=sharing) (2s for 1k pairwise 1k peaks, vs 40ms).

### CODE REVIEW

**Comment by niekdejonge** [comment]
@florian-huber Seems like a great change to me, but I am less familiar with this part of the code base. Could you check and merge this PR?

**Comment by niekdejonge** [comment]
@tornikeo please feel free to add yourself to the citation.cff file, btw!

**Comment by tornikeo** [comment]
Oh, wait a sec... Once I remove pytorch matmul from the picture, numpy seems only around 2x faster, not 50x times faster. This is all on CPU. It's weird to have such a difference between cpu-pytorch and numpy.

Still investigating this. Just a 2x acceleration might not be worth more obscure code.

**Comment by niekdejonge** [comment]
Hmm yes, surprising that the difference is that large. Still 2x acceleration can be worth it, I will leave it up to @florian-huber. Let us know what comes out of the investigation :)

**Comment by tornikeo** [comment]
Found the culprit. It's because [numpy only uses BLAS for floaty types](https://github.com/numpy/numpy/issues/14556). There's no integer support for BLAS matmul. Still numpy is slower than torch. With this, we arrive to around 10x speedup.

I've also expanded the [comparison notebook](https://colab.research.google.com/drive/1dYvdcbkUUOubgjPAZTtsfpG5Z7duc1kw?usp=sharing) to compare all three approaches (numpy, torch and njit).

**Comment by florian-huber** [comment]
Hi @tornikeo ,
sorry, I am a bit slow in the moment but will try to look more into this asap.

**Comment by florian-huber** [comment]
Performance boost indeed looks great!
I also tested this for different sizes (number of vectors):
image


Interestingly, I found no noticeable difference between the numpy and the torch implementation. Definitely nothing worth adding torch as a dependency. I would stick with the new numpy implementation as suggested by @tornikeo !

(here is my adaption of your notebook: https://colab.research.google.com/drive/1Ru1SjUzMlF3ejHAX1dbMGRRENyGTRJau?usp=sharing)

**Comment by florian-huber** [comment]
I will first merge this into a local branch (`numpy_replace_njitted`) to have all tests running.

**Pull request merged**
