### PR TITLE
Install sphinxcontrib.apidoc on readthedocs

### PR DESCRIPTION
**Pull request by sverhoeven**
The build on readthedocs is failing with 
```
Extension error:
Could not import extension sphinxcontrib.apidoc (exception: No module named 'sphinxcontrib.apidoc')
```

This PR installs the develop dependencies during readthedocs build.

I configured this branch to be [build](https://readthedocs.org/projects/matchms/builds/15022214/) at readthedocs and it is green. See https://matchms.readthedocs.io/en/rtd-apidoc/ ,

After PR is merged/closed this PR branch should be removed on https://readthedocs.org/projects/matchms/versions/

### CODE REVIEW

**Comment by florian-huber** [comment]
Oh, looks like the linter became stricter...

**Review by florian-huber — APPROVED** [review]
Thanks for fixing this @sverhoeven.
I also dealt with the linting complaints from an pylint update (--> #257). So, when merging master into this branch, tests should pass.

**Comment by florian-huber** [comment]
Just to avoid confusion: I will merge master into this branch. And if all tests pass I will merge it (and delete the branch + the branch on readthedocs).

**Comment by sverhoeven** [comment]
Go for it

**Pull request merged**
