### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by florian-huber**

### CODE REVIEW

**Comment by florian-huber** [comment]
Running into some conda errors here when trying to fix #116 (limiting sphinx to <3.2.0 at least for now seems to fix it). 
Any short hints on that @fdiblen or @sverhoeven ?
Error is: 
``ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::archspec-0.1.1-pyh9f0ad1d_0'.``

(seems to happen when it updates conda on windows)

**Comment by sverhoeven** [comment]
Try to upgrade https://github.com/marketplace/actions/setup-miniconda action in .github/workflows/conda_build.yml to latest version (v1.6.0).

**Comment by florian-huber** [comment]
Thanks a lot Stefan, changing the miniconda-version seems to fix it!

**Review by sverhoeven — APPROVED** [review]
What bad luck to have 2 dependency issues at the same time.

[Build](https://readthedocs.org/projects/matchms/builds/11644848/) of branch on readthedocs fails due to latest sphinx installation after environment-dev.yml is installed. Sphinx 3.2.1 should be released next weekend. So build should work after that.

**Comment by florian-huber** [comment]
Thanks for reviewing.

**Pull request merged**
