### PR TITLE
Added `require_retention_time` and `require_retention_index` filters

### LINKED ISSUE #585: Add filters `require_retentiontime` and `require_retentionindex`
These filters would be useful to for example remove entries from a database that don't have retention time or retention index information.

Each filter should be its own function that takes a spectrum and either returns the same spectrum if it has `retention_index` / `retention_time` set to a valid value or None if otherwise.

An example is available [here](https://github.com/matchms/matchms/blob/master/matchms/filtering/metadata_processing/require_precursor_mz.py).

### LINKED ISSUE #603: Development setup bugs
**Describe the bug**
Poetry installing dev dependencies fails on Ubuntu 22.04 with Python 3.12

**Screenshots**
```
$ poetry install --no-root --with=dev
Updating dependencies
Resolving dependencies... (30.7s)

Package operations: 55 installs, 4 updates, 0 removals

  • Installing llvmlite (0.40.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  /tmp/tmpret6ixy_/.venv/bin/python /tmp/tmpf1capkqf/llvmlite-0.40.1/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/tmpf1capkqf/llvmlite-0.40.1/ffi/build.py", line 227, in <module>
      main()
    File "/tmp/tmpf1capkqf/llvmlite-0.40.1/ffi/build.py", line 217, in main
      main_posix('linux', '.so')
    File "/tmp/tmpf1capkqf/llvmlite-0.40.1/ffi/build.py", line 135, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/tmp/tmpret6ixy_/.venv/bin/python' failed with exit code 1
  

  at ~/micromamba/envs/matchms-dev/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with llvmlite (0.40.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "llvmlite (==0.40.1)"'.

  • Downgrading numpy (1.26.4 /home/conda/feedstock_root/build_artifacts/numpy_1707225359967/work/dist/numpy-1.26.4-cp312-cp312-linux_x86_64.whl -> 1.24.4): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
  
  Traceback (most recent call last):
    File "/home/hechth/micromamba/envs/matchms-dev/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/hechth/micromamba/envs/matchms-dev/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 994, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "/tmp/tmpg2iizb02/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
      import distutils.core
  ModuleNotFoundError: No module named 'distutils'
  

  at ~/micromamba/envs/matchms-dev/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.24.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.24.4)"'.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS via WSL

### PR DESCRIPTION
**Pull request by hechth**
Added filter functions and related tests by @wverastegui

Also reduced the upper bound for supported python versions from 3.12 to 3.11

closes #585 
closes #603

### CODE REVIEW

**Comment by hechth** [comment]
@florian-huber I have no idea why the documentation is failing, I think otherwise everything is fine - something related to old docstrings which where not changed at some PRs that changed the respective code I assume

**Comment by niekdejonge** [comment]
@hechth I think the documentation issue in #611

**Comment by niekdejonge** [comment]
@hechth and @wverastegui I added the option to only keep spectra if they are within a specified rt window. Would you agree with this addition? Otherwise I will revert the last two commits.

**Review by hechth — COMMENTED** [review]
@niekdejonge thanks for the additions!

**Comment by hechth** [comment]
@florian-huber @niekdejonge looks good to me, so I think we can merge this :)

**Comment by niekdejonge** [comment]
I agree, I will merge it now, thanks @hechth

**Pull request merged**
