### PR TITLE
Rearranged test in folders

### LINKED ISSUE #391: Rearrange tests in folders
Since there are plenty of tests, it might be better to rearrange them into folders regarding the different topics to make things a bit more organized.

### PR DESCRIPTION
**Pull request by zargham-ahmad**
This PR includes the following: 

- arranged tests in folders #391
- arranged testdata in folder
- updated testdata path in tests
- updated pesticides.mgf path in README.rst and index.rst
- fixed test_save_as_mgf and updated py_mgf.write in save_as_mgf function as per the change in [pyteomics 4.6](https://github.com/levitsky/pyteomics/releases)

closes #391

### CODE REVIEW

**Review by hechth — APPROVED** [review]

**Comment by hechth** [comment]
https://github.com/levitsky/pyteomics/issues/111

**Comment by zargham-ahmad** [comment]
_Note: Had to close and reopen multiple times to trigger CI because of the current CI configuration in order to fix the CI issue_

**Comment by hechth** [comment]
@florian-huber I think this should make the testing folder a bit more organized and easier to extend in the future

**Review by florian-huber — APPROVED** [review]
Thanks @zargham-ahmad for restructuring the tests folder!
Feel free to merge (or let me know if I should merge it).

**Pull request merged**
