### PR TITLE
add negative ionmode adducts

### PR DESCRIPTION
**Pull request by florian-huber**
I added 3 negative ionmode adducts which I encountered several times when working with GNPS data to the table of known adducts.

### CODE REVIEW

**Comment by florian-huber** [comment]
@justinjjvanderhooft, I added 3 negative ionmode adducts that I frequently encountered in the dataset. To keep good practices (4 eyes before we merge it 😄 ) --> can you briefly check they are OK?

Obviously the list is still not exhaustive, but we can always add more later. Or people can suggest additional ones if they encounter them.

**Comment by justinjjvanderhooft** [comment]
@florian-huber I can see the ones you added, but could you indicate how you annotated them? That is not completely clear to me from the code lines. I.e., what is "Ser"? And what is the source of the annotations?

**Comment by florian-huber** [comment]
Good question Justin!
The `[M-H]-/[M-Ser]-` was just added because we had `[M-H-/M-Ser]-` on the list. That, however, doesn't answer the question of what `Ser` is... but there were quiet some of those in the all-GNPS dataset.
We could also remove these two "known adducts" and add a conversion rule that will simply take the first `[M-H]-` part into account?

**Comment by justinjjvanderhooft** [comment]
So am I right that these added annotations came from the list of GNPS with higher-frequency adduct annotations? In that case, it makes sense to add them but only if we understand their origin. I mean, Ser could refer to Serine, but I am not quite sure that this is a thing in mass spec (I haven't seen it yet....)

**Comment by florian-huber** [comment]
Just send out a tweet to see if some mass-spec people respond and point us to something for `[M-Ser]-`...

**Comment by florian-huber** [comment]
OK. I now removed the `Ser` adducts from the known adduct table (seems they are not really adducts).
I added them to the list of our conversion rules so that `[M-H]-/[M-Ser]- --> [M-H]-` and `[M-H-/M-Ser]- --> [M-H]-`

**Comment by florian-huber** [comment]
@justinjjvanderhooft I will merge the changes for now (see above comment). But we can always return to this issue and update our lists with some community help!

**Pull request merged**
