### PR TITLE
Update CI_build.yml

### PR DESCRIPTION
**Pull request by florian-huber**

### CODE REVIEW

**Comment by florian-huber** [comment]
Hi @sverhoeven !
I here tried a few things to fix the failing conda verify tests in #230, but with no success.
Do you have any further ideas how to solve this --> #232 ?

**Comment by sverhoeven** [comment]
I will have a look at it on 10 Jun 2021

**Comment by sverhoeven** [comment]
I would suggest we to remove the conda building workflows from this repo as use https://anaconda.org/bioconda/matchms and their [build system](https://bioconda.github.io/contributor/build-system.html) for building and verifying.

There are some things we can do to make the bioconda package more integrated
1.  ~When doing a GH release/PyPI release then trigger a version update in bioconda using https://bioconda.github.io/contributor/updating.html#updating-recipes~ seems to already be working, see https://github.com/bioconda/bioconda-recipes/pull/28382
2. ~Adding more tests to https://github.com/bioconda/bioconda-recipes/blob/master/recipes/matchms/meta.yaml~  [bioconda](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/matchms/meta.yaml) is recommending not to run unit tests on their system

From `.github/workflows/CI_build.yml` I think we should keep the `anaconda_dev` job, but remove `anaconda_build` and `anaconda_verify` jobs.
We keep `.github/workflows/conda_publish.yml` so we can run the matchms test suite using the bioconda package.

**Comment by florian-huber** [comment]
Outdated --> will be closed

**Pull request closed without merging**
