### PR TITLE
add Python 3.9 support

### PR DESCRIPTION
**Pull request by florian-huber**
Address (part of) #240.

### CODE REVIEW

**Review by sverhoeven — CHANGES_REQUESTED** [review]
Looks good. 

However I would also use python 3.9 in the .github/workflows/CI_build.yml:first_check job and 3.9 in test_with_conda job.

And I would also add 3.9 to classifiers in setup.py, see https://github.com/matchms/matchms/blob/4c7de6bf9586b8092a62e952731b0a009a6e67f7/setup.py#L44

**Comment by florian-huber** [comment]
Good points Stefan.
I added it to `setup.py`. But I ran into issues with `typing` hints between 3.8 and 3.9, so I left the pylint testing with 3.8.

**Review by sverhoeven — APPROVED** [review]
Hmm, typing errors seems to be false positive of old pinned pylint version in prospector, see https://github.com/PyCQA/prospector/issues/418

**Comment by florian-huber** [comment]
Thanks for reviewing Stefan!

**Pull request merged**
